---
all:
  vars:
    ansible_connection: ssh
    ansible_user: vagrant
    ansible_become_password: vagrant
  children:
    master:
      hosts:
        master1.elanza48.dev:
           ansible_host: 172.27.48.11
           ansible_ssh_private_key_file: ../.vagrant/credentials/ssh/master-1/ssh-key
    worker:
      hosts:
        worker1.elanza48.dev:
          ansible_host: 172.27.48.21
          ansible_ssh_private_key_file: ../.vagrant/credentials/ssh/worker-1/ssh-key